### ISSUE TITLE
Cannot find name Given

### ISSUE THREAD

**Issue by batbrain9392** [hirezio/given#1] opened 2020-08-26 10:08 UTC
**Describe the bug**
Given/When/Then global types not found after installation and configuration.
VS Code error: `Cannot find name 'Given'`

**To Reproduce**

1. Install dependency `@hirez_io/jasmine-give`
2. Add `@hirez_io/jasmine-given` to the `types` array in `tsconfig.spec.json`
3. Add `require('@hirez_io/karma-jasmine-given')` to the `plugins` array and `@hirez_io/jasmine-given` to the `frameworks` array in `karma.config.js`
4. Save all files and restart the Angular Language Server (or restart VS Code)
5. Try to write Given/When/Then in any spec file

**Expected behavior**
Given/When/Then global types should be recognised.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/16289648/91289441-42c60c00-e78a-11ea-8aa4-83f63d9a1ecf.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.1 LTS
- IDE: VS Code
- Version: 1.48.1

**Additional context**
VS Code addtional info -
Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:11:59.963Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

**Comment by elira** [comment] 2020-08-26 10:14
Hi @batbrain9392 , I edited tsconfig.json too, with the following additions:
```
"types": [
      "jasmine",
      "@hirez_io/jasmine-given", // <-- ADD THIS

      // ...any other types you might have...
    ],
```
```
"typeRoots": [
  "node_modules/@types",
  "node_modules" // <-- ADD THIS
],

```

**Comment by batbrain9392** [comment] 2020-08-26 10:31
Sorry, I forgot to add that. But even then, it's the same issue.

But on adding `node_modules` to `typeRoots`, a whole bunch of additional errors popup:
**Cannot find type definition file for '@angular'.**

**Comment by batbrain9392** [comment] 2020-08-26 11:02
I was able to solve the Given/When/Then types problem by adding **node_modules/@hirez_io** instead of `node_modules` to the `typeRoots` array in `tsconfig.json`.

But that spawns a small issue: `Cannot find type definition file for 'karma-jasmine-given'.`
I checked in the `karma-jasmine-given` folder for a **.d.ts** file, but none was there.

**Comment by shairez** [comment] 2020-08-26 13:13
Thanks for the report @batbrain9392 !

Can you please share the contents of your `tsconfig.json`? (and which Angular version are you using)

as I can't seem to reproduce the error you're getting (mine is not complaining, so I'm guessing it's a difference in the tsconfig settings). 

@elira thanks for chiming in and helping, do you also see a similar error in `karma.conf.js` ?

**Comment by elira** [comment] 2020-08-26 13:43
It works on my side. Thanks @shairez .

**Comment by batbrain9392** [comment] 2020-08-27 11:03
> Thanks for the report @batbrain9392 !
> 
> Can you please share the contents of your `tsconfig.json`? (and which Angular version are you using)
> 
> as I can't seem to reproduce the error you're getting (mine is not complaining, so I'm guessing it's a difference in the tsconfig settings).
> 
> @elira thanks for chiming in and helping, do you also see a similar error in `karma.conf.js` ?

angular **8.1.0**
tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@hirez_io",
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "bf-ui-lib": [
        "dist/bf-ui-lib"
      ],
      "bf-ui-lib/*": [
        "dist/bf-ui-lib/*"
      ]
    }
  }
}
```

If we provide just `node_modules` in tsconfig typeRoots, this is the situation:

![screenshot](https://user-images.githubusercontent.com/16289648/91434925-6e65f680-e85d-11ea-95e5-e32086139c18.png)

**Comment by shairez** [comment] 2020-08-27 11:22
You need to also add

```
    "types": [
      "@hirez_io/jasmine-given"
    ],
```

To the `tsconfig.json` to remove the "Given" error, because VSCode doesn't look at the `tsconfig.spec.json` unfortunately.

But the Angular errors are super weird... I have basically the same config as you have (except for the `paths` which I don't have) and I don't see these errors (and I tried it on multiple projects)

Did you have any issues with your `yarn install -D @hirez_io/jasmine-given` by any chance?

**Comment by batbrain9392** [comment] 2020-08-28 07:45
> I was able to solve the Given/When/Then types problem by adding **node_modules/@hirez_io** instead of `node_modules` to the `typeRoots` array in `tsconfig.json`.
> 
> But that spawns a small issue: `Cannot find type definition file for 'karma-jasmine-given'.`
> I checked in the `karma-jasmine-given` folder for a **.d.ts** file, but none was there.

No problems during installation. And the Given error and Angular errors were all solved when I added this to the tsconfig:
```
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@hirez_io",
    ],
```

But the new error is `Cannot find type definition file for 'karma-jasmine-given'.`

**Comment by shairez** [comment] 2020-08-28 13:20
What's weird is that `karma-jasmine-given` doesn't have a declaration file because it's not written in TS.

Also, karma.conf.js is a "js" file... so what does it care about the declaration file.

That's why I say, there's something more to the configuration than what we see (maybe a vs code plugin, or some setting or something like that).

Is there a way for you to post this project on github (or a similar one with the same configuration) so we could try and simulate the problem ourselves?

**Comment by batbrain9392** [comment] 2020-08-31 13:30
This is proprietary software, so I don't think I can. But I'll try to recreate it in a personal project if I can and post that here.

**Comment by shairez** [comment] 2020-08-31 21:42
Thanks @batbrain9392 !

Even a small project with the same environment `tsconfig.json` files and other configs etc that shows you the same errors could help tremendously

**Comment by shairez** [comment] 2020-09-08 21:56
Just thought about something... try to add the location of `karma.config.js` to your `exclude: []` property in `tsconfig.json`

That should get rid of the "Cannot find type definition file for 'karma-jasmine-given'." issue

**Comment by shairez** [comment] 2020-09-30 08:00
Hi @batbrain9392 

Did you try my latest suggestion?

**Comment by shairez** [comment] 2020-10-24 17:53
I'm closing the issue for now (we spoke privately)

Feel free to re-open whenever it becomes relevant again

**Closed as completed by shairez** 2020-10-24 17:53 UTC
Labels: need more info

**Comment by batbrain9392** [comment] 2020-11-04 20:03
> Hi @batbrain9392
> 
> Did you try my latest suggestion?

I couldn't in that project. But I'll try that when I get a chance in some other, if I face the same issue. Thanks a lot for your help Shai.

**Comment by shairez** [comment] 2020-11-04 20:21
No problem @batbrain9392 !
Thanks for the report!
